# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@master
        with:
          name: page
          path: dist
          if-no-files-found: error
  deploy:
    # Add a dependency to the build job
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@master
      with:
        name: page
        path: .
    - name: Replace string in file
      uses: MathieuSoysal/replace-string-in-file@v1.0.0
      with:
        file: index.html
        old-string: '<base href="\/"\/>'
        new-string: '<base href="\/AzureAppSettingsParser\/"\/>'
    - uses: actions/configure-pages@v1
    - uses: actions/upload-pages-artifact@v1
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@main
